// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = Microsoft.VisualStudio.TestTools.UITest.Input.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public partial class UIMap
    {
        
        #region Properties
        public UIStartmenüWindow UIStartmenüWindow
        {
            get
            {
                if ((this.mUIStartmenüWindow == null))
                {
                    this.mUIStartmenüWindow = new UIStartmenüWindow();
                }
                return this.mUIStartmenüWindow;
            }
        }
        
        public UISzd1Window UISzd1Window
        {
            get
            {
                if ((this.mUISzd1Window == null))
                {
                    this.mUISzd1Window = new UISzd1Window();
                }
                return this.mUISzd1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIStartmenüWindow mUIStartmenüWindow;
        
        private UISzd1Window mUISzd1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIStartmenüWindow : XamlWindow
    {
        
        public UIStartmenüWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "Start menü";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("Start menü");
            #endregion
        }
        
        #region Properties
        public UIKitűzöttcsempékList UIKitűzöttcsempékList
        {
            get
            {
                if ((this.mUIKitűzöttcsempékList == null))
                {
                    this.mUIKitűzöttcsempékList = new UIKitűzöttcsempékList(this);
                }
                return this.mUIKitűzöttcsempékList;
            }
        }
        #endregion
        
        #region Fields
        private UIKitűzöttcsempékList mUIKitűzöttcsempékList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIKitűzöttcsempékList : XamlList
    {
        
        public UIKitűzöttcsempékList(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlList.PropertyNames.AutomationId] = "groupItems";
            this.WindowTitles.Add("Start menü");
            #endregion
        }
        
        #region Properties
        public UIGoogleChromecsoportjGroup UIGoogleChromecsoportjGroup
        {
            get
            {
                if ((this.mUIGoogleChromecsoportjGroup == null))
                {
                    this.mUIGoogleChromecsoportjGroup = new UIGoogleChromecsoportjGroup(this);
                }
                return this.mUIGoogleChromecsoportjGroup;
            }
        }
        #endregion
        
        #region Fields
        private UIGoogleChromecsoportjGroup mUIGoogleChromecsoportjGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UIGoogleChromecsoportjGroup : XamlControl
    {
        
        public UIGoogleChromecsoportjGroup(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.ControlType] = "Group";
            this.SearchProperties["AutomationId"] = "{77ac0480-9597-4474-aed5-f95e069f4f06}";
            this.WindowTitles.Add("Start menü");
            #endregion
        }
        
        #region Properties
        public XamlListItem UISzd1ListItem
        {
            get
            {
                if ((this.mUISzd1ListItem == null))
                {
                    this.mUISzd1ListItem = new XamlListItem(this);
                    #region Search Criteria
                    this.mUISzd1ListItem.SearchProperties[XamlListItem.PropertyNames.AutomationId] = "tile-P~b07035b1-30d9-4a7c-81de-b16376ee8713_vw2e7bp5pxcky!App";
                    this.mUISzd1ListItem.WindowTitles.Add("Start menü");
                    #endregion
                }
                return this.mUISzd1ListItem;
            }
        }
        #endregion
        
        #region Fields
        private XamlListItem mUISzd1ListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26621.2")]
    public class UISzd1Window : XamlWindow
    {
        
        public UISzd1Window()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "szd1";
            this.SearchProperties[XamlControl.PropertyNames.ClassName] = "Windows.UI.Core.CoreWindow";
            this.WindowTitles.Add("szd1");
            #endregion
        }
        
        #region Properties
        public XamlButton UIFillominoButtonButton
        {
            get
            {
                if ((this.mUIFillominoButtonButton == null))
                {
                    this.mUIFillominoButtonButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIFillominoButtonButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "fillominoButton";
                    this.mUIFillominoButtonButton.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUIFillominoButtonButton;
            }
        }
        
        public XamlButton UISokobanButtonButton
        {
            get
            {
                if ((this.mUISokobanButtonButton == null))
                {
                    this.mUISokobanButtonButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUISokobanButtonButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "sokobanButton";
                    this.mUISokobanButtonButton.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUISokobanButtonButton;
            }
        }
        
        public XamlComboBox UILevelChooserComboBox
        {
            get
            {
                if ((this.mUILevelChooserComboBox == null))
                {
                    this.mUILevelChooserComboBox = new XamlComboBox(this);
                    #region Search Criteria
                    this.mUILevelChooserComboBox.SearchProperties[XamlComboBox.PropertyNames.AutomationId] = "levelChooser";
                    this.mUILevelChooserComboBox.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUILevelChooserComboBox;
            }
        }
        
        public XamlButton UIReloadButton
        {
            get
            {
                if ((this.mUIReloadButton == null))
                {
                    this.mUIReloadButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIReloadButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "reloadButton";
                    this.mUIReloadButton.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUIReloadButton;
            }
        }
        
        public XamlComboBox UIAlgorithmChooserComboBox
        {
            get
            {
                if ((this.mUIAlgorithmChooserComboBox == null))
                {
                    this.mUIAlgorithmChooserComboBox = new XamlComboBox(this);
                    #region Search Criteria
                    this.mUIAlgorithmChooserComboBox.SearchProperties[XamlComboBox.PropertyNames.AutomationId] = "algorithmChooser";
                    this.mUIAlgorithmChooserComboBox.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUIAlgorithmChooserComboBox;
            }
        }
        
        public XamlButton UISolveButton
        {
            get
            {
                if ((this.mUISolveButton == null))
                {
                    this.mUISolveButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUISolveButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "solveButton";
                    this.mUISolveButton.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUISolveButton;
            }
        }
        
        public XamlButton UIBackButton
        {
            get
            {
                if ((this.mUIBackButton == null))
                {
                    this.mUIBackButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUIBackButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "backButton";
                    this.mUIBackButton.WindowTitles.Add("szd1");
                    #endregion
                }
                return this.mUIBackButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlButton mUIFillominoButtonButton;
        
        private XamlButton mUISokobanButtonButton;
        
        private XamlComboBox mUILevelChooserComboBox;
        
        private XamlButton mUIReloadButton;
        
        private XamlComboBox mUIAlgorithmChooserComboBox;
        
        private XamlButton mUISolveButton;
        
        private XamlButton mUIBackButton;
        #endregion
    }
}
